### ISSUE TITLE
[Bug]: syntaxError: ..  is not valid JSON | The engine no longer downloads or starts

### ISSUE THREAD

**Issue by shk100** [CheshireCaat/puppeteer-with-fingerprints#137]
Hello, 
Since today, on several of my projects, the plugin no longer works and I get a json error message when I try to launch a browser.
 And I've tried to start from scratch in an empty project with the default test code and the same problem with paid and free versions, I've also tried updating the plugin but no download , and always Json error.

Everything has been working for several weeks and without changing anything I've had this problem since this morning, thank you for your help.

Example code : 

```
const { plugin } = require("puppeteer-with-fingerprints");

plugin.setServiceKey("");

(async () => {
  // Get a fingerprint from the server:
  const fingerprint = await plugin.fetch({
    tags: ["Microsoft Windows", "Chrome"],
  });

  // Apply fingerprint:
  plugin.useFingerprint(fingerprint);

  // Launch the browser instance:
  const browser = await plugin.launch({
    headless: false, // Garde l'interface visible
    args: ["--lang=fr-FR,fr", "--ignore-certificate-errors"], // Ignorer les erreurs de certificat
    timeout: 60000, // Temps d'attente maximal pour le lancement du navigateur
  });

  // The rest of the code is the same as for a standard `puppeteer` library:
  const page = await browser.newPage();
  await page.goto("https://google.com");
})();
```

Terminal output : 
```
undefined:1
<himl>
syntaxError: Unexpected token '<, "«html> <h"... is not valid JSON
at JSON-parse (<anonymous»)
at IncomingMessage.<anonymous> (C: \xxxx\projet\node _modules \bas-remote-node\src\services\utils.js:15:22)
at IncomingMessage.emit (node:events:531:35)
at endReadableNT (node: internal/streams/readable:1696:12)
at process-processTicksAndRejections (node: internal/process/task_queues:82:21)
```

System 
 - Plugin version [1.4.4]
 - Puppeteer [23.3.0]
 - Node version [20.17.0]

**Comment by CheshireCaat** [comment]
Hello, there are problems on the server side - you need to update the plugin to the latest version or wait for a solution (today or tomorrow everything should be fixed).

I recommend the first option, since in recent versions the dependence on the server has been significantly reduced.

**Comment by singhaditya4** [comment]
+1

**Comment by singhaditya4** [comment]
> Hello, there are problems on the server side - you need to update the plugin to the latest version or wait for a solution (today or tomorrow everything should be fixed).
> 
> I recommend the first option, since in recent versions the dependence on the server has been significantly reduced.

update doesn't do anything

**Comment by bablosoft** [comment]
> I have the same error, everything worked yesterday, any solution?

You need to update your npm module

**Comment by krais006** [comment]
> Thanks to the dev for the quick response !!
> 
> In the end what worked was:
> 
> npm uninstall puppeeter-with-fingerprints
> 
> npm i puppeeter-with-fingerprints

thanks I did it and I still have the same error ;/

**Comment by bablosoft** [comment]
> thanks I did it and I still have the same error ;/

I don't think that it is possible to get same error.

**Comment by OnlineTrackerWhatsApp** [comment]
![image](https://github.com/user-attachments/assets/6f91c78d-f0d6-4e2d-b465-60422969187d)

**Comment by krais006** [comment]
[20:40:34] Fetching Fingerprint...
undefined:1
<html>
^

SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Users\krais\Desktop\acc\node_modules\bas-remote-node\src\services\utils.js:15:22)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.17.0
PS C:\Users\krais\Desktop\acc>

**Comment by bablosoft** [comment]
In order to fix it, please update puppeteer-with-fingerprints

**Comment by krais006** [comment]
I did it, I still have this error

**Comment by bablosoft** [comment]
Okay, you can provide access, I will check it out mail.to.twaego@gmail.com

**Comment by krais006** [comment]
Yesterday everything was still working for me :/

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\krais\Desktop\microsoft-account-creator-main\1> npm uninstall puppeteer-with-fingerprints
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'node-gyp-load@0.0.5',
npm warn EBADENGINE   required: { node: '>=16.0.0', npm: '^8.5.0' },
npm warn EBADENGINE   current: { node: 'v20.17.0', npm: '10.8.2' }
npm warn EBADENGINE }

removed 29 packages, and audited 136 packages in 1s

16 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\krais\Desktop\microsoft-account-creator-main\1> npm i puppeteer-with-fingerprints
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'node-gyp-load@0.0.5',
npm warn EBADENGINE   required: { node: '>=16.0.0', npm: '^8.5.0' },
npm warn EBADENGINE   current: { node: 'v20.17.0', npm: '10.8.2' }
npm warn EBADENGINE }

added 29 packages, and audited 165 packages in 5s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\krais\Desktop\microsoft-account-creator-main\1> node app.js
Warning: the "fetch" method signature with two parameters is deprecated. Please use the new syntax for options together with the "setServiceKey" method usage instead.
Try the full version of the fingerprint service which has advantages over the free one:

- Emulate fingerprints for other platforms and browsers.
- Increased limits when receiving a fingerprints from the service.
- Filters by tags, versions, screen resolution and many other parameters.
- Popular perfect canvas queries are already included in the received fingerprints.

If you want to buy the full version, please visit this website - https://bablosoft.com/directbuy/FingerprintSwitcher/2.
C:\Users\krais\Desktop\microsoft-account-creator-main\1\node_modules\browser-with-fingerprints\src\plugin\connector\engine.js:100
          throw new InvalidEngineError(`Unable to start engine process (code: ${error.code})`);
          ^

InvalidEngineError: Unable to start engine process (code: ENOENT)
This could be due to the fact that the engine was not downloaded or unpacked correctly.
Try completely deleting the engine folder and restarting the code until it completes.
If this does not help, open an issue with a detailed description of the problem.
    at C:\Users\krais\Desktop\microsoft-account-creator-main\1\node_modules\browser-with-fingerprints\src\plugin\connector\engine.js:100:17
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.17.0
PS C:\Users\krais\Desktop\microsoft-account-creator-main\1>

**Comment by krais006** [comment]
I managed to fix it, I uninstalled and installed it several times, now it works. Thanks

**Comment by OnlineTrackerWhatsApp** [comment]
It is working fine now.

**Comment by silvestrodecaro** [comment]
Updating the plugin worked for me, thanks for your work!

**Comment by dr3adx** [comment]
> Hello, there are problems on the server side - you need to update the plugin to the latest version or wait for a solution (today or tomorrow everything should be fixed).
> 
> I recommend the first option, since in recent versions the dependence on the server has been significantly reduced.

will this issue be fixed? upgrading to newest version is not a solution since all mobile fingerprints are flagged (>= 127)

**Comment by CheshireCaat** [comment]
@dr3adx how this ticket related to the pixelscan problem? Of course it will be fixed, I will let you know separately.

> since all mobile fingerprints are flagged

Not all, I offered you options, even taking into account a small number of fingerprints of the required sizes.

**Comment by dr3adx** [comment]
> @dr3adx how this ticket related to the pixelscan problem? Of course it will be fixed, I will let you know separately.
> 
> > since all mobile fingerprints are flagged
> 
> Not all, I offered you options, even taking into account a small number of fingerprints of the required sizes.

I meant is the JSON error server issue gonna be fixed so we can use older engine versions?

**Comment by bablosoft** [comment]
Only English

**Comment by CheshireCaat** [comment]
The problem with the servers has been resolved at the moment, the scripts are available again, but I still recommend updating to the latest version so as not to depend on it.
