### ISSUE TITLE
Explanation for why this package is only compatible with Windows?

### ISSUE THREAD

**Issue by tab1293** [CheshireCaat/puppeteer-with-fingerprints#28]
I have puppeteer running on a remote Linux based server and would like to be able to change the fingerprint of the browser running in this environment. I understand that this package only works for Windows, but I was hoping you could elaborate on why this is the case. 

Is there work that the community can help you with to help unlock additional OS support? If not, are there any other fingerprinting solutions for non Windows environments that you can recommend? 

Thanks!

**Comment by CheshireCaat** [comment]
All plugins depend on [bas-remote-node](https://github.com/CheshireCaat/bas-remote-node) which itself depends on **BAS** engine.
The last one only supports the **Windows** operating system and it may not change in the future.

Only developers can fix this completely, so the community will not be able to implement full support.

Personally, I can't suggest other solutions than `puppeteer-extra-plugin-stealth`, but it is much worse in terms of anonymity and provides only a minimum of features compared to the engine in these plugins.

**Comment by bablosoft** [comment]
In order to replace fingerprint reliably, browser source must be changed.
If it was done through js injections, such type of substitution is easy to detect.

Linux support requires several time consuming tasks:

1. Porting OS specific patches, like font replacement, dynamically changing DPI, etc.
2. Additional patches which will make Linux system look like Windows and Android. We already maintain one direction Windows - Android and it requires a lot of code.
3. We have several patches which prevents detection of running software on Windows server instead of desktop. And there should be much more for Linux.
4. Chrome source is constantly changes. All this new patches must be merged each month with new Chromium release.

And of course there will be new Linux specific bugs.

My recommendation is to start browser on same OS that you are trying to emulate, otherwise it will be much easier to detect.
