### ISSUE TITLE
exports.loader = new Loader('puppeteer', '19.1.0', ['puppeteer-core']) and utils.js file;

### ISSUE THREAD

**Issue by soya-miruku** [CheshireCaat/puppeteer-with-fingerprints#52]
Hey just a quick one, is there a reason why version 19.1.0 is put here for puppeteer? and if i were to change it to the latest one, would that cause any issues?

also within the utils file there is the line browser.version, but from my understanding this should be an async function call, is this not using puppeteer browser object?

thanks.

**Comment by CheshireCaat** [comment]
> Hey just a quick one, is there a reason why version 19.1.0 is put here for puppeteer? and if i were to change it to the latest one, would that cause any issues?

The loader indicates the minimum version on which the plugin was tested - when using a version lower, an error will be generated. If you increase it, there will be no problems, but why is this necessary?

> also within the utils file there is the line browser.version, but from my understanding this should be an async function call, is this not using puppeteer browser object?

It's just property check for the `Browser` type because the `bindHooks` method potentially can be called with the `BrowserContext` type. It's not a function call, it seems to me that this is obvious from the code.
