### ISSUE TITLE
What about storage? 

### ISSUE THREAD

**Issue by marcusdiy** [CheshireCaat/puppeteer-with-fingerprints#55]
It uses too much storage and it increases after each run! Is there some cleanup function to run on exit or what? 
Each time a new profiles folder is created. How to reuse them or delete them?

**Comment by CheshireCaat** [comment]
The plugin automatically deletes unused versions of the engine, as well as unused configuration files.

Memory may grow due to the creation of temporary profiles - the plugin does not delete them itself, you have to do this logic yourself. Profiles are stored in the root folder of the engine, as specified in the documentation. This way, for example, you can clean out a folder before starting work, removing all unnecessary data.

**Comment by marcusdiy** [comment]
How do I know wich folder to delete? Im trying to setup a parallel and continuos run

**Comment by CheshireCaat** [comment]
Just use a custom path to the profile, then you will know exactly where and what profile is located, and you can manipulate them at any time, and also safely delete all temporary ones:

You can limit yourself to just your own pattern, saving profiles in the same location, but temporary ones under a different name - for example `plugin-prof-1`, `plugin-prof-2` and so on.

**Comment by marcusdiy** [comment]
Ok, will do. Thanks.
