### ISSUE TITLE
Lock is not acquired/owned by you

### ISSUE THREAD

**Issue by xploader** [CheshireCaat/puppeteer-with-fingerprints#58]
When I run this function in multithreading I get an error
`
```
const fs = require('fs');
async function main(ip, instance) {
    
  const {plugin} = require('puppeteer-with-fingerprints'); 
  let path_prof = `./engine_br/${instance}/profiles`;
  try{
    fs.rmdirSync(path_prof, { recursive: true });
  }
  catch{
    console.log('y');
  }
  let fingerprint = await plugin.fetch('some_key', {
      tags: ['Microsoft Windows', 'Chrome']
    });
  plugin.useProxy(ip).useFingerprint(fingerprint).setWorkingFolder(`./engine_br/${instance}`);
  console.log(`Finger has set`,`./engine_br/${instance}`)
  const browser = await plugin.launch(
    {headless:true, 
    });
  
  console.log('Browser started');
  const page = await browser.newPage();
  console.log('New page open');
  try{
    page.goto('Https://google.com')
  }
  catch(error){
    console.log('Erorr Hapen.Lets retartf app!');
  }
  finally{
      await browser.close();
      console.log('Deleting Folder...');
      fs.rmdirSync(path_prof, { recursive: true });
    }
  
};
module.exports = main;`

```
And the script that starts the threads

```
`const fs = require('fs');
const configFile = 'Config_app.json';
const config = JSON.parse(fs.readFileSync(configFile));
const instance_list = config.BotInstances;
const logic = require('./logic.js')


async function runInstances() {
  while (true) {
    const promises = instance_list.map((instance) => {
      const instance_name  = instance.instance;
      const ip = instance.ip;
      return logic(ip, instance_name)
        .then(() => {
          console.log(`Main function completed for instance: ${instance_name}`);
        })
        .catch((error) => {
          console.error(`An error occurred for instance ${instance_name}:`, error);
        });
    });

    await Promise.all(promises)
      .then(() => {
        console.log('All instances completed successfully.');
      })
      .catch((error) => {
        console.error('An error occurred:', error);
      });
  }
}

runInstances().catch((error) => {
  console.error('An error occurred:', error);
});`
```

I get this error after few minutes.. 
```
`C:\Users\Administrator\Desktop\cleanJSCR\node_modules\proper-lockfile\lib\lockfile.js:285
            return callback(Object.assign(new Error('Lock is not acquired/owned by you'), { code: 'ENOTACQUIRED' }));
                                          ^

Error: Lock is not acquired/owned by you
    at C:\Users\Administrator\Desktop\cleanJSCR\node_modules\proper-lockfile\lib\lockfile.js:285:43
    at LOOP (node:fs:2816:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ENOTACQUIRED'
}

Node.js v21.0.0`
```

**Comment by CheshireCaat** [comment]
I can't reproduce your lock file error, but your code has a number of issues that need to be fixed and kept in mind:

1. You should change the working folder **BEFORE** any interaction with the plugin. In your example, the plugin for the first call will first install the engine in the standard folder, only to request a fingerprint. And this will continue in the same way - for the next call the previous folder will be used when requesting a fingerprint. This is incorrect logic, so you should set the folder before requesting a fingerprint.
2. The `setWorkingFolder` method was made as an alternative to environment variables, hence the need for the logic described in the paragraph above. Also, using it is not thread safe as stated [here](https://github.com/CheshireCaat/browser-with-fingerprints/issues/11#issuecomment-1700167330). Therefore, I would recommend that you use additional synchronization when changing a folder - for example through `async-lock`.
3. The multithreading option is easier to implement through worker threads or an alternative, so that each client has its own process, in which case you will not need to worry about synchronization when using different folders, and all work will be completely parallel.

I recommend using at least the first and second tips and fixing your code, this may also help solve the problem with lock files - if there are other problems, please open a new ticket.
